AWSTemplateFormatVersion: "2010-09-09"
Description: ""

Parameters:
  ClusterName:
    Type: String
    Description: The unique name for this cluster
    AllowedPattern: ^[0-9A-Za-z][A-Za-z0-9\-_]*
    Default: eks-cluster-dev

  SubnetIpBlocks:
    Type: CommaDelimitedList
    Description: Comma-delimited list of three CIDR blocks
    Default: 10.0.48.0/24, 10.0.112.0/24, 10.0.176.0/24

#  ClusterControlPlaneSecurityGroup:
#    Description: The security group of the cluster control plane.
#    Type: AWS::EC2::SecurityGroup::Id

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: arn:aws:iam::578120814996:role/AmazonEKSClusterRole  # mandatory
      ResourcesVpcConfig: # mandatory
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds: # specify at least two subnets
          - !Ref Subnet1
          - !Ref Subnet2
        EndpointPublicAccess: false
        EndpointPrivateAccess: true
#        PublicAccessCidrs: [ "0.0.0.0/0" ]
      Version: 1.23
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit

  VPC:
    # https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default

  SecurityGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
    Type: AWS::EC2::SecurityGroup
    Properties:
#      GroupName: "eks-cluster"
      GroupDescription: allow connections from specified CIDR ranges
#      SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: 80
#          ToPort: 80
#          CidrIp: 0.0.0.0/0
#        - IpProtocol: tcp
#          FromPort: 22
#          ToPort: 22
#          CidrIp: 192.168.1.1/32
      VpcId: !Ref VPC
      Tags:
        - Key: !Sub kubernetes.io/cluster/${ClusterName}
          Value: owned

  Subnet1:
    # https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#network-requirements-subnets
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      # the select function allows selection across a list
      CidrBlock: !Select [ 0, !Ref SubnetIpBlocks ]
      AvailabilityZone: !Select [0, !GetAZs ""]  #eu-west-1a
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      # the select function allows selection across a list
      CidrBlock: !Select [ 1, !Ref SubnetIpBlocks ]
      AvailabilityZone: !Select [1, !GetAZs ""]  #eu-west-1b


#  aws cloudformation create-stack --stack-name eks-cluster-stacks --template-body file://eks.yaml