AWSTemplateFormatVersion: "2010-09-09"
Description: Manages IAM roles on AWS account
#Parameters:
#  AmazonEKSClusterPolicy:
#    Type: String
#    Description: 'ARN of the IAM Policy to add to the role'

Resources:
  EKSClusterRole: # creates IAM role 'AmazonEKSClusterRole'
    Type: AWS::IAM::Role
    Properties:
      RoleName: AmazonEKSClusterRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: eks.amazonaws.com
              AWS: arn:aws:iam::578120814996:user/sesan
      Description: "creates an Amazon EKS cluster IAM role"
      ManagedPolicyArns: [arn:aws:iam::aws:policy/AmazonEKSClusterPolicy]




# aws cloudformation create-stack --stack-name iam-roles-stacks --template-body file://iam-roles.yaml --capabilities CAPABILITY_NAMED_IAM